### ISSUE TITLE
Missing blank pages when language is not slovak in the Sci template

### ISSUE THREAD

**Issue by krejciadam** [Witiko/fithesis3#11]
Hi! I found what I think is a bug in the template for sci.muni. 

When I change the language from slovak by: 

`\usepackage[main=english, english, czech, slovak, german, russian]{babel} `
or
`\usepackage[main=czech, english, czech, slovak, german, russian]{babel} `

the blank pages that should be after the title page, bibliographic entry etc. to ensure correct twoside layout disappear. It only works correctly for

`\usepackage[main=slovak, english, czech, slovak, german, russian]{babel} `

I'm using the current Overleaf version.

Thanks!
Adam

**Comment by Witiko** [comment]
Hi,

there is a good reason for that behavior. When you use `czech` or `english` as the locale, then only the Czech and English versions of the mandatory parts (bibliographic entry, abstract) need to be typeset, which means that they can be typeset side-by-side:

![screenshot_20171022_224952](https://user-images.githubusercontent.com/603082/31866214-9568eab8-b77c-11e7-8ce0-c1322b3eeb34.png)

When you use `slovak` as the locale, then the Czech, English, and Slovak versions of the mandatory parts (bibliographic entry, abstract) all need to be typeset, which means that fithesis3 has to break them apart:

![screenshot_20171022_225403](https://user-images.githubusercontent.com/603082/31866227-c24cc31a-b77c-11e7-9ec0-f87f0c35c10d.png)
