### ISSUE TITLE
Problems with package 'todonotes'

### ISSUE THREAD

**Issue by astaruch** [Witiko/fithesis3#18]
Hi,

there exists a package 'todonotes', which makes a writing of TODO notes convenient ([Overleaf link](https://www.overleaf.com/latex/examples/example-formatted-todonotes/qmpbkcqxfgmg)). 

If you take the template of 'todonotes' on Overleaf and compile it, this is the expected result:
![Screenshot from 2019-10-22 17-04-57](https://user-images.githubusercontent.com/13131548/67300442-3af46600-f4ee-11e9-9df3-af2505b92d38.png)

When I take fithesis template and try to add 'todonotes', only inline version of todo is working as expected:
![Screenshot from 2019-10-22 17-11-16](https://user-images.githubusercontent.com/13131548/67300921-0634de80-f4ef-11e9-95eb-441ab7fdf000.png)

Here is the [link](https://www.overleaf.com/read/sbshgnsfbvvv) on Overleaf with minimum working example.

**Comment by astaruch** [comment]
I've found a warning in the log on the Overleaf:

    Package todonotes Warning: The length marginparwidth is less than 2cm and will most likely cause issues with the appearance of inserted todonotes. The issue can be solved by adding a line like \setlength {\marginparwidth }{2cm} prior to loading the todonotes package. on input line 143.

After adding the line in the document:

    \setlength {\marginparwidth }{2cm} 

problem is solved.

![Screenshot from 2019-10-22 17-18-34](https://user-images.githubusercontent.com/13131548/67301663-01245f00-f4f0-11e9-9b46-3291c06629b0.png)

**Comment by Witiko** [comment]
Thank you for the report.
This is an open issue, since `\marginparwidth` is zero in fithesis, which is clearly wrong and does not reflect the actual layout.
