### ISSUE TITLE
Vertical text alignment

### ISSUE THREAD

**Issue by europ** [Witiko/fithesis3#20]
#### Problem

The provided fithesis3 template does not align the text properly with respect to vertical alignment.

The text might be configured to be vertically fully justified or it might be due to the image size, which moved the image to the next page.

NOTE: The image placement option must be exactly '*precise location*' (`[H]`). I need to put the image exactly behind the specific paragraph and before the following paragraph as it is shown in the example.

How can I solve this problem (move the text on the left page up to the section title - remove the huge unwanted space between section title and text)? Is there any option if my image will move to another page, the text on the previous page will be aligned to the top of the page? Thanks.

#### Example

[example.pdf](https://github.com/Witiko/fithesis/files/4239538/out.pdf)

![Screenshot from 2020-02-22 16-37-36](https://user-images.githubusercontent.com/22373707/75095076-ad0ab380-5591-11ea-81c4-b2580aa349d4.png)

**Comment by europ** [comment]
There is a possible workaround by using the `\newpage` command before the image, which will keep the text on the page vertically aligned to the top and move the image on a new page. This solution is not the best, but works.

**Comment by Witiko** [comment]
In fithesis3, page content is equalized, i.e. the text height is always the same. You can use the `\raggedbottom` command at the beginning of your document, which will relax this constraint, i.e. some pages will be shorter but the text will always be vertically aligned to the top. This will do what you are asking for.

Note that it is generally best to avoid `[H]` on tables and figures. Instead, you can refer to tables and figures using the `\label` and `\ref` commands:

```tex
\begin{figure}
...
\caption{My beautiful figure.}
\label{fig:beautiful}
\end{figure}

The results are more beautiful than what you might expect, see Figure~\ref{fig:beautiful}.
```
This way, you as the author do not need to care if a table or figure ends up on a different page. The reader will be able to find it regardless using the table or figure number.
