### ISSUE TITLE
Change "paper" to "thesis" in the English version of the declaration part

### ISSUE THREAD

**Issue by cermmik** [Witiko/fithesis3#22]
Currently, the declaration part contains the following text:
> Hereby I declare that this paper is my original authorial work, which ...

Although it is technically correct, it will be more suitable to write "thesis" instead of "paper". (I know that I can define my declaration text in `\thesissetup{}`, but not everyone will notice it.)

**Comment by Witiko** [comment]
Fithesis can be also used to typeset thesis proposals and seminar papers, so perhaps we should replace `paper` with `\thesis@@{typeName}` to get a sensible output for various types of text.
