### ISSUE TITLE
Add faculty of Pharmacy

### ISSUE THREAD

**Issue by slonik923** [Witiko/fithesis3#23]
From 1.7. MUNI has new faculty: [Masaryk University Faculty of Pharmacy](https://www.pharm.muni.cz/).
It will be nice to add this new faculty in template, so students can choose this faculty in preamble, and the headings, logos and so on will be typesetted correctly.

I understand this template is mainly used by FI students, but PHARM student`s don`t have any LaTeX template available (only [Word template](https://is.muni.cz/auth/do/pharm/studijni_dokumenty/magisterske_studium/cesky_studijni_program/)) and it will be really nice to use this template.
Maybe also talk with PHARM management about this.

**Comment by Witiko** [comment]
@Slonik923 Hello and thanks for touching base with us.

The LaTeX templates will be switching over to JVS 2018 in near future. Support for the Faculty of Pharmacy should be added after this conversion rather than before, since we don't have logos for the Faculty of Pharmacy, only the JVS 2018 logotypes.

**Comment by slonik923** [comment]
Can you get me some time estimate? Will it be ready in the spring semester 2021? I am asking on behalf of Pharmacy students, because they can`t use this LaTeX template (no Pharm logos), neither VFU template, so their only option is to use new MUNI Word template, which is not ideal.

**Comment by Witiko** [comment]
It ought to be ready in spring 2021, a student is working on the conversion to JVS 2018 as a part of her thesis.

**Comment by Witiko** [comment]
Closed by https://github.com/xvrabcov/fithesis/pull/23.
