### ISSUE TITLE
Footnote index resets per chapter

### ISSUE THREAD

**Issue by mik-jozef** [Witiko/fithesis3#24]
Despite the documentation claiming that "Each footnote is uniquely numbered across the entire document as per the formal
requirements of the faculty", the footnote counter resets.

I used the fithesis4 template on Overleaf, and added the following lines to file `fi-pdflatex.tex`:

```
\chapter{A}

Asdf \footnote{asdf}.

\chapter{B}

Bsdf \footnote{bsdf}.
```

Both footnotes are numbered 1.

Read-only example: https://www.overleaf.com/read/bngyjqzkmvrz

**Comment by Witiko** [comment]
@mik-jozef [The documentation](http://mirrors.ctan.org/macros/latex/contrib/fithesis/fithesis.pdf#page=91) only promises that fithesis will uniquely number footnotes for the Faculty of Law, not the Faculty of Informatics: https://github.com/Witiko/fithesis/blob/3c878cfaeffc0b0498a6d38c34214fa179a6d338/style/mu/law.dtx#L39-L44

We could easily extend fithesis to do the same for the Faculty of Informatics, but [the formal requirements of the Faculty of Informatics](https://is.muni.cz/auth/do/fi/uredni_deska/predpisy/smernice/Smernice_dekana_1_2021_zaverecne_prace.pdf) say nothing about footnotes. If you would like your footnotes to be uniquely numbered, you can just enter the above code before `\begin{document}` in your document. Please, let me know if there is any other way I can help.

**Comment by mik-jozef** [comment]
Thank you, I had not realized I was looking at a part of the documentation related to the Faculty of Law. Including `
 \counterwithout{footnote}{chapter} ` in my thesis solved my issue.
