### ISSUE TITLE
LyX Layout

### ISSUE THREAD

**Issue by Stanton731** [Witiko/fithesis3#25]
Hello,
I am contacting you to ask if it would be possible to create a layout for the WYSIMYM editor of Latex, **LyX**.
This is a tool that inherently brings Latex closer to non-technical users, and thus I believe that creating a layout for using the `fithesis4` class would make this diploma template more accessible to a wider number of students.
There is currently a Lyx layout for the `fithesis2` class [(available here)](https://github.com/Darkless012/fithesis2c/blob/master/lyx/fithesis2.layout), but this is out of date as of today and the author of the layout is unlikely to update it.
Thank you.

**Comment by Witiko** [comment]
This could be an interesting project for a bachelor's thesis.

**Comment by Witiko** [comment]
This issue has been migrated to <https://gitlab.fi.muni.cz/external_relations/document_templates/fithesis/-/issues/25>.
