### ISSUE TITLE
make complete fails to find fithesis3.cls

### ISSUE THREAD

**Issue by janinko** [Witiko/fithesis3#5]
When running `make complete` LaTeX failed to find `fithesis3.cls` file. 
There is however file `./fithesis3.cls` in the root folder.
Complete output: https://gist.github.com/janinko/60050ef4d65518debbe6

**Comment by Witiko** [comment]
Unlike `make all`, `make complete` also typesets the guides and the examples. These expect the class, style, locale, and logo files to be installed in the TeX distribution. Therefore you either need to run `make install` prior to running `make complete` (see the README), or clone the fithesis3 repo directly to a directory inside a TeX distribution tree (such as `~/.texmf-var/tex/latex`). In the latter case, no installation is necessary and `make complete` just works™.

**Comment by janinko** [comment]
In the readme, there is this order of commands:

> To begin the installation, execute the following command from within the current directory:
> 
> ```
>     make complete
>     make install to=[[TDS]]
> ```

If I do:
`make all` works
`make install` seems to install fithesis3.cls successfully but then complains with:

```
# Documentation
mkdir -p "/usr/share/texlive/texmf-local/doc/latex/fithesis"
cp --parents --verbose fithesis.pdf guide/mu/econ.pdf guide/mu/fi.pdf guide/mu/fsps.pdf guide/mu/fss.pdf guide/mu/law.pdf guide/mu/med.pdf guide/mu/ped.pdf guide/mu/phil.pdf guide/mu/sci.pdf "/usr/share/texlive/texmf-local/doc/latex/fithesis"
cp: nelze získat informace o „fithesis.pdf“: Adresář nebo soubor neexistuje
guide -> /usr/share/texlive/texmf-local/doc/latex/fithesis/guide
guide/mu -> /usr/share/texlive/texmf-local/doc/latex/fithesis/guide/mu
cp: nelze získat informace o „guide/mu/econ.pdf“: Adresář nebo soubor neexistuje
cp: nelze získat informace o „guide/mu/fi.pdf“: Adresář nebo soubor neexistuje
cp: nelze získat informace o „guide/mu/fsps.pdf“: Adresář nebo soubor neexistuje
cp: nelze získat informace o „guide/mu/fss.pdf“: Adresář nebo soubor neexistuje
cp: nelze získat informace o „guide/mu/law.pdf“: Adresář nebo soubor neexistuje
cp: nelze získat informace o „guide/mu/med.pdf“: Adresář nebo soubor neexistuje
cp: nelze získat informace o „guide/mu/ped.pdf“: Adresář nebo soubor neexistuje
cp: nelze získat informace o „guide/mu/phil.pdf“: Adresář nebo soubor neexistuje
cp: nelze získat informace o „guide/mu/sci.pdf“: Adresář nebo soubor neexistuje
Makefile:143: návod pro cíl „install“ selhal
make: *** [install] Chyba 1
```

Which is probably because `make complete` wasn't done.

I think there is cyclic dependency on the commands:
`make complete` needs to have fithesis installed, but `make install` expects that `make complete` was already run.

**Comment by Witiko** [comment]
That is a good catch.

**Comment by Witiko** [comment]
That is a good catch. https://github.com/Witiko/fithesis3/commit/5cd75b184f5af39ed54608515c047b4a23baff4d and https://github.com/Witiko/fithesis3/commit/1234ddcf40f6996e5709fed6686c7aa69fd055b2 should close the issue. I added the `base`, `install-base`, `docs`, and `install-docs` make targets. You install the base class using the `base` and `install-base` targets. You can then optionally typeset and install the documentation using the `docs` and `install-docs` targets. Consult the updated [`README`](https://github.com/Witiko/fithesis3/blob/master/README.md) for further information.
