### ISSUE TITLE
macOS --parents

### ISSUE THREAD

**Issue by daemontus** [Witiko/fithesis3#7]
Related to issue #2, macOS does not support `--parents` flag also for the `cp` command. Actually, `cp` does not support the `--` option syntax at all (not sure why O.o). Fortunately, the installation works fine after removing all unsupported flags (since all directories are created by `mkdir`anyway, and `--verbose` is just verbose).

**Comment by Witiko** [comment]
If you have the time, please send me a pull request. I don't have an apple device to test the Makefile on.

**Comment by daemontus** [comment]
Sure, see #8

**Comment by Witiko** [comment]
Please confirm that 1ef13c2 fixes this issue.

**Comment by Witiko** [comment]
Please confirm that branch `fix-mac-install` fixes your issue. I tested the patch on the Mac OS X boxes in the PC hall at FI, MU.

**Comment by daemontus** [comment]
Apologies, examination period combined with thesis deadline hit my timetable hard :D Just tested your fix, everything seems ok, thank you very much.

**Comment by Witiko** [comment]
I am glad to hear that, thank you for the feedback.
